# Automatically updated by the winget bot at 2021/Feb/11
Id: Google.ChromeBeta
Publisher: Google
Name: Google Chrome Beta
Author: Google
Description: A fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and so much more.
AppMoniker: chrome-beta
Tags: Browser, Google, Chromium
FileExtensions: html, htm, url
Protocols: http, https
Homepage: https://www.google.com/chrome/beta/
License: Proprietary freeware, based on open source components
LicenseUrl: https://www.google.com/chrome/terms/
MinOSVersion: 10.0.0.0
Version: 68.73.16431
InstallerType: msi
Installers:
- Arch: x64
  Url: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  Sha256: F5E8D1C3A78431F285B080FBD8B02213D53F7AC78F33784BA23CA6B3FD8A51C8
  Scope: machine
  Language: en-US
  ProductCode: "{0575054B-2ECB-338C-869D-87E4DA51E237}"
