Id: Microsoft.PowerBI
Name: PowerBI Desktop
AppMoniker: PowerBI
Version: 2.81.5831.621
Publisher: Microsoft
License: Copyright (c) Microsoft Corporation. All rights reserved.
LicenseUrl: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
MinOSVersion: 10.0.0.0
Homepage: https://powerbi.microsoft.com/
Tags: "reporting, analytics, microsoft, powerbi"
InstallerType: exe
Installers:
  - Arch: x64
    Url: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
    Sha256: 819C3CC735B4EBC42277EF056691183C9229BBFAD308724BDC80E1127D7DA015
    Language: en-US
    Switches:
      Silent: "-q -norestart ACCEPT_EULA=1"
      SilentWithProgress: " -passive -norestart ACCEPT_EULA=1"