# Automatically updated by the winget bot at 2020/Dec/24
Id: Microsoft.PowerBI
Publisher: Microsoft Corporation
Name: PowerBI Desktop
Author: Microsoft
Description: Create stunning reports and visualizations with Power BI Desktop. It puts visual analytics at your fingertips with intuitive report authoring. Drag-and-drop to place content exactly where you want it on the flexible and fluid canvas. Quickly discover patterns as you explore a single unified view of linked, interactive visualizations.
AppMoniker: PowerBI
Tags: reporting, analytics, microsoft, powerbi
Homepage: https://powerbi.microsoft.com/
License: Copyright (c) Microsoft Corporation. All rights reserved.
LicenseUrl: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
MinOSVersion: 10.0.0.0
Version: latest
Switches:
  Custom: -norestart ACCEPT_EULA=1
  Silent: -quiet
  SilentWithProgress: -passive
InstallerType: exe
Installers:
- Arch: x64
  Url: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  Sha256: 60c2c7d6acef914c65b0c3a5bb7e8589ddf3af00f395f806c91329e7549d7528
  Scope: machine
  Language: en-US
