Id: Jackett.Jackett
Publisher: Jackett
Name: Jackett
Version: 0.17.570
License: GNU General Public License v2.0
InstallerType: EXE
Tags: torrent, p2p, rss, proxy
Description: API Support for your favorite torrent trackers.
Homepage: https://github.com/Jackett/Jackett
Installers:
  - Arch: x64
    Url: https://github.com/Jackett/Jackett/releases/download/v0.17.570/Jackett.Installer.Windows.exe
    Sha256: e12d01f1ba07578528e643704b2a5a0469506502ed1a65b41ec8e66c50643cbd
    Switches:
      Silent: /VERYSILENT
      SilentWithProgress: /VERYSILENT
