Id: Microsoft.BotFrameworkEmulator
Publisher: Microsoft Corporation
Name: Bot Framework Emulator
Version: 4.9.0
License: Copyright (c) Microsoft Corporation - MIT
LicenseUrl: https://github.com/microsoft/BotFramework-Emulator/blob/master/LICENSE.txt
AppMoniker: botframework-emulator
Tags: bot, framework, emulator
Description: Development tool for the Microsoft Bot Framework. Allows developers to test and debug bots on localhost.
Homepage: https://github.com/microsoft/BotFramework-Emulator
Installers:
  - Arch: x64
    InstallerType: EXE
    Url: https://github.com/microsoft/BotFramework-Emulator/releases/download/v4.9.0/BotFramework-Emulator-4.9.0-windows-setup.exe
    Sha256: EDE23BCAD7200D83EFFE6621534D654CBB986ECCADB4E1E35B9EA50C7EF220B8
    Switches:
      Silent: /S
      SilentWithProgress: /S
