Id: KDE.Krita
Publisher: KDE
Name: Krita
Version: 4.2.9.0
License: GNU GENERAL PUBLIC LICENSE
InstallerType: nullsoft
LicenseUrl: https://github.com/KDE/krita/blob/master/COPYING
Description: Krita is a professional FREE and open source painting program. It is made by artists that want to see affordable art tools for everyone.
Homepage: https://krita.org/en/
Installers:
  - Arch: x64
    InstallerType: nullsoft
    Url: https://ftp.gwdg.de/pub/linux/kde/stable/krita/4.2.9/krita-x64-4.2.9-setup.exe
    Sha256: fd8345a4d4170c62e410f8cfe1547bb811eb312de953a540b3bf12bb79137b9f