Id: PlotSoft.PDFill
Version: 14.0 Build 2
Name: PDFill
Publisher: PlotSoft
License: Freeware
AppMoniker: pdfill
Tags: PDF Tools
Description: Free PDF Tools.
Homepage: https://www.pdfill.com/
Installers:
  - Arch: x64
    Url: https://www.plotsoft.com/download/PDFill_X64.msi
    InstallerType: msi
    Sha256: 1046c8c5ac460f2b5f3436a1020b9ff825d0e0ea3d5a32df299c19311c2908ab
