Id: 4KDownload.4KVideoDownloader
Publisher: 4K Download
Name: 4K Video Downloader
Version: 4.14.3
License: See in https://www.4kdownload.com/agreement/freeware.
InstallerType: MSI
LicenseUrl: https://www.4kdownload.com/agreement/freeware
AppMoniker:
Tags: video-downloader, youtube, vimeo
Description: Free Video Downloader
Homepage: https://www.4kdownload.com/products/product-videodownloader
Installers:
  - Arch: x64
    InstallerType: msi
    Url: https://dl.4kdownload.com/app/4kvideodownloader_4.14.3_x64.msi
    Sha256: 55b731916569bff92cf97fd4817cc4b6f2e385a8f85ae7360f2077bd5a13ac26
