# ================== General ==================

Id: Mozilla.Thunderbird.Thunderbird_v78.1.0
Version: 78.1.0
Name: Thunderbird (English US)
Publisher: Mozilla
AppMoniker: thunderbird
Tags: thunderbird, email, eMail, E-mail, email Client
Description: Thunderbird is a free email application that’s easy to set up and customize!

# ================== License ==================

Homepage: https://www.thunderbird.net
License: Mozilla Public License Version 2.0
LicenseUrl: https://www.mozilla.org/en-US/MPL/2.0/

# ================= Installer =================

Installers:
  - Arch: x64
    Url: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/78.1.0/win64/en-US/Thunderbird%20Setup%2078.1.0.msi
    Sha256: 7F779DD397E06E76E356FCD2C4C9BC5DAD7A1334881516E25242D769D7B84BD9
    InstallerType: msi
    Switches:
          Custom: /norestart
          Silent: /qn
          SilentWithProgress: /qb
