Id: MediaArea.MediaInfo-GUI
Publisher: MediaArea
Name: MediaInfo-GUI
AppMoniker: mediainfo-gui
Version: 20.03
License: BSD-2-Clause
LicenseUrl: https://mediaarea.net/MediaInfo/License
Description: Convenient unified display of the most relevent technical and tag data for video and audio files.
Homepage: https://mediaarea.net/MediaInfo
Tags: video metadata
FileExtensions: 264, 3g2, 3ga,3gp, 3gpa, 3gpp, aa3, aac, aacp, adts, ac3, act, aif, aifc, aiff, amr, ape, asf, at3, au, avi, avs, bdmv, bmp, bms, caf, clpi, dat, dde, divx, dpg, dff, dsd, dts, dv, dvr, dvr-ms, eac3, evo, h3d, f4a, f4b, f4v, fla, flac, flc, fli, flv, gif, gis, gvi, h264, hdmov, ifo, ism, isma, ismv, j2k, jpeg, jpg, jps, m1s, m1t, m1v, m2p, m2s, m2t, m2ts, m2v, m4a, m4b, m4v, mac, mk3d, mka, mks, mkv, mlp, mod, mov, mp+, mp2, mp3, mp4, mpc, mpd, mpe, mpeg, mpg, mpgv, mpgx, mpls, mpm, mpo, mpv, mts, mxf, oga, ogg, ogm, ogv, ogx, oma, opus, png, pns, qcp, qt, ra, rm, rmvb, shn, smv, spdif, stl, spx, swf, tak, thd, thd+ac3, tif, tiff, tmf, tp, trec, trp, ts, tta, ty, vob, vqf, vro, w64, wav, webm, wma, wmv, wtv, wv, wvc, y4m
InstallerType: nullsoft
Switches:
  Silent: /S
  SilentWithProgress: /S
Installers:
  - Arch: x64
    Url: https://mediaarea.net/download/binary/mediainfo-gui/20.03/MediaInfo_GUI_20.03_Windows.exe
    Sha256: 1b3c461b84150ce000f5ba41f507115911d612a86294c11a5fec3bc03d671761
# ManifestVersion: 0.1.0
