Id: Axosoft.GitKraken
Name: GitKraken
Version: 7.1.0
Publisher: Axosoft
Homepage: https://www.gitkraken.com/
Description: Git GUI Client.
License: Commercial (c) 2020 Axosoft, LLC.
LicenseUrl: https://www.gitkraken.com/eula
InstallerType: Exe
Installers:
  - Arch: x64
    Url: https://release.gitkraken.com/win64/GitKrakenSetup.exe
    Sha256: F851DCE69FF9CB39E71373B70B3926C3433AF7632E7B65670DE225B334CCE5A9
    Switches:
      Silent: /silent
      SilentWithProgress: /silent

