Id: GNU.Emacs
Version: 27.0.91
Name: GNU Emacs
Publisher: GNU Project
License: GPL
AppMoniker: emacs
Tags: gnu, emacs, text editor, utility, tool
Description: An extensible, customizable, free/libre text editor - and more.
Homepage: https://www.gnu.org/software/emacs/
Installers:
  - Arch: x64
    Url: https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.0.91-x86_64-installer.exe
    Sha256: D11A4C7588116102DDC0480A1467D6F13A5DC7C77BCB0715B3FAD3F5DC4D9F5D
    InstallerType: nullsoft
