Id: OpenVPNTechnologies.OpenVPN
Name: OpenVPN
AppMoniker: OpenVPN
Version: 2.5.0
Publisher: Open VPN Technologies
Author: Open VPN Technologies
License: Copyright © 2020 OpenVPN Inc
LicenseUrl: https://openvpn.net/license/
MinOSVersion: 10.0.0.0
Homepage: https://openvpn.net/
Tags: "vpn, private, connection, network, virtual private connection, openvpn"
InstallerType: msi
Installers:
  - Arch: x64
    Url: https://swupdate.openvpn.org/community/releases/OpenVPN-2.5.0-I601-amd64.msi
    Sha256: a27d15a64bfa966d2775a8008aed049181773555b4e74b42cb63a18f58d9fd4c
    Language: en-US
