Id: KDE.Kate
Version: 20.04.2-938
Name: Kate
Publisher: KDE
License: LGPL-2.0
LicenseUrl: https://www.gnu.org/licenses/lgpl-3.0.html
AppMoniker: kate
Tags: kde, kate editor
Description: Kate is a multi-document editor part of KDE since release 2.2. Being a KDE applications, Kate ships with network transparency, as well as integration with the outstanding features of KDE.
Homepage: https://kate-editor.org/
Installers:
  - Arch: x64
    Url: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/938/artifact/kate-20.04.2-938-windows-msvc2019_64-cl-sideload.appx
    Sha256: e7acc4cd118a6996bc123b8ddbf8d41bfcb01ca707b17e48918e7b6b0472f86e
    InstallerType: appx
