Id: Automattic.Simplenote
Version: 2.6.0
Name: Simplenote
Publisher: Automattic
License: GPLv2
LicenseUrl: https://raw.githubusercontent.com/Automattic/simplenote-electron/develop/LICENSE.md
AppMoniker: simplenote
Description: Simplenote is an easy way to keep notes, lists, ideas and more. Your notes stay in sync with all your devices for free.
Homepage: https://simplenote.com/
Installers:
  - Arch: x64
    Url: https://github.com/Automattic/simplenote-electron/releases/download/v2.6.0/Simplenote-win-2.6.0-x64.appx
    Sha256: 6197f1ab70a6c6abe7fa4da257b287de720f02cbd2c958f478f978ef2311ff6e
    InstallerType: appx
    #PackageFamilyName: "simplenote_cdagv53c87npa"
