Id: DMM.GamePlayer
Version: 2.5.5
Name: DMM Game Player
Publisher: DMM
License: Copyright (c) since 1998 DMM
AppMoniker: dmmgameplayer
Tags: dmm, gameplayer
Homepage: https://games.dmm.com/
Installers:
  - Arch: x86
    Url: https://dl-gameplayer.dmm.com/admin/win/installer/DMMGamePlayerSetup.exe
    Sha256: B28195834DB4433E79CE43A078A99E34F68665665051CF24BED9CF9E47896B86
    InstallerType: inno
