Id: LutzRoeder.Netron
Version: 4.4.9
Name: Netron
Publisher: Lutz Roeder
AppMoniker: netron
Description: Visualizer for neural network, deep learning and machine learning models
License: Copyright (c) Lutz Roeder
Homepage: https://github.com/lutzroeder/netron
Installers:
  - Arch: x86
    InstallerType: nullsoft
    Url: https://github.com/lutzroeder/netron/releases/download/v4.4.9/Netron-Setup-4.4.9.exe
    Sha256: C81C788957836D26C4EC5786982DF51BEC33B6D4A43862FAB8B609F1CEFA1E71
