Id: TimKosse.FileZillaClientNightly
Name: FileZilla Client Nightly
AppMoniker: filezilla-nightly
Version: 3.52.2-20210217
Publisher: Tim Kosse
Author: Tim Kosse
License: (c) 2021 Tim Kosse
LicenseUrl: https://filezilla-project.org/license.php
Description: FileZilla Client is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.
Homepage: https://filezilla-project.org/
Installers:
  - Arch: x64
    Url: https://filezilla-project.org/nightlies/2021-02-17/win64/FileZilla_3_setup.exe
    Sha256: 32f2a28d3bef9f8ce2c7d9faab7093b7dc6ad3561250b325e417a75ad6ee4873
    InstallerType: nullsoft
