# Automatically updated by the winget bot at 2021/Feb/10
Id: GuinpinSoft.MakeMKV
Version: v1.15.4
Name: MakeMKV
Publisher: GuinpinSoft
License: Copyright © 2008-2020 GuinpinSoft inc
LicenseUrl: https://www.makemkv.com/aboutmkv/
AppMoniker: makemkv
Description: MakeMKV is your one-click solution to convert video that you own into free and patents-unencumbered format that can be played everywhere.
Homepage: https://www.makemkv.com/
Installers:
- Arch: Neutral
  Url: https://www.makemkv.com/download/Setup_MakeMKV_v1.15.4.exe
  Sha256: 80F9B56F8BCA14E847AC86FB2B3DB574A79DBE4BA557832FE238A3F370C60C8E
  InstallerType: nullsoft
