Id: Google.Chrome
Publisher: Google
Name: Chrome
Description: A fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and so much more.
Homepage: https://www.google.com/chrome/
Tags: Browser, Google, Chromium
License: Proprietary freeware, based on open source components
LicenseUrl: https://www.google.com/chrome/terms/
Version: 83.0.4103.116
InstallerType: exe
Installers:
  - Arch: x64
    Url: https://dl.google.com/edgedl/chrome/install/ChromeStandaloneSetup64.exe
    Sha256: C595D478CF9C57FD9C546CEBB4B1C157E14131D795BFF6EAC15461971FBF074F
    Language: en-US
    Switches:
      Silent: "/installsource taggedmi /silent /install \"appguid={8A69D345-D564-463C-AFF1-A69D9E530F96}&iid={7DF7C924-72F2-9B35-53F5-9837D6B76D3F}&lang=en&browser=5&usagestats=0&appname=Google%20Chrome&needsadmin=false&ap=x64-stable-statsdef_1&installdataindex=empty\" /installelevated /nomitag"
      SilentWithProgress: "/installsource taggedmi /silent /install \"appguid={8A69D345-D564-463C-AFF1-A69D9E530F96}&iid={7DF7C924-72F2-9B35-53F5-9837D6B76D3F}&lang=en&browser=5&usagestats=0&appname=Google%20Chrome&needsadmin=false&ap=x64-stable-statsdef_1&installdataindex=empty\" /installelevated /nomitag"
