# ================== General ==================
Id: Google.Chrome
Publisher: Google
Name: Chrome
Author: Google
Description: A fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and so much more.
AppMoniker: googlechrome
Tags: Browser, Google, Chromium
FileExtensions: http, https

# ================== License ==================
Homepage:  https://www.google.com/chrome/
License: Proprietary freeware, based on open source components
LicenseUrl: https://www.google.com/chrome/terms/

# ================= Installer =================
MinOSVersion: 10.0.0.0
#Channel: stable                # Channel is not supported in this preview (5/24/2020)
Version: 84.0.4147.105

Switches:
      Custom: /norestart
      Silent: /quiet
      SilentWithProgress: /passive
      #Interactive:
      Language: en-US

InstallerType: msi
Installers:
  - Arch: x64
    Url: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi
    Sha256: aeb9e0bfe85943884d2ea0a309642fc7cae13c0fadebc17c241d63bea8e3076a
    Scope: machine
  #- Arch: x86                  # Support for multiple installers are not supported in this preview (5/24/2020)
    #Url: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
    #Sha256: 791175d54476e80314be90b92e02a78915bbace8ec7071da6305089114a21fab
    #Scope: machine
    
# ManifestVersion: 0.1.0
