# Automatically updated by the winget bot at 2021/Feb/10
Id: Caphyon.AdvancedInstaller
Name: Advanced Installer
AppMoniker: advinst
Version: 17.9
Publisher: Caphyon
License: © Caphyon 2002 - 2020 Ltd. All rights reserved.
LicenseUrl: https://www.advancedinstaller.com/eula.html
MinOSVersion: 10.0.0.0
Homepage: https://AdvancedInstaller.com/
InstallerType: MSI
Installers:
- Arch: x64
  Url: https://www.advancedinstaller.com/downloads/advinst.msi
  Sha256: 7FCA2A91EB43266DCDC51414C93CC939642A795C67CA6361297AF97F477971B9
